### ISSUE TITLE
https release timeline

### ISSUE THREAD

**Issue by yazdan** [ActiveCampaign/postmark-rails#95]
Hi, 

As you know, Postmark is deprecating `http` api endpoints. I saw that you already have updated the code here https://github.com/ActiveCampaign/postmark-rails/commit/c96a57984a9b80bda4a7603019fc2e03e0be6e8e
but I was wondering when you will release the ruby gem so we can update

Thanks

**Comment by balvig** [comment]
Hello @yazdan,

Sorry for the late reply! 🙇 

`postmark-rails` relies on [`postmark-gem`](https://github.com/ActiveCampaign/postmark-gem), which switched to using SSL by default since version `1.3.1`, [quite some time ago](https://github.com/ActiveCampaign/postmark-gem/commit/00a8e0264daaf51fff7b1a4c3adf8ebd7fb91eea). 

If you're on a semi-recent version of that gem and have no custom configuration, ie something like this:

```rb
config.action_mailer.postmark_settings = {   secure: false # disables SSL }
```

...then in theory you should be using `https` already.
Let me know if that's not the case and I can help trying to debug!

**Comment by yazdan** [comment]
@balvig Thanks for your answer,

I checked our code and it is using not latest but pretty recent version of `postmark-gem`.
I will investigate more and will reopen this issue if I found any.

Thanks
